/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author migue
 */
public class JPanelUpdateVehiculo extends javax.swing.JPanel {

    private clsParqueadero auxParqueadero;

    public JPanelUpdateVehiculo(clsParqueadero objParqueadero) {
        this.auxParqueadero = objParqueadero;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        lblNumPuertas = new javax.swing.JLabel();
        lblTipoCaja = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        cmbNumPuertas = new javax.swing.JComboBox<>();
        cmbTipoCaja = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DIGITAR LOS DATOS DEL VEHICULO A ACTUALIZAR");

        lblPlaca.setText("PLACA DEL VEHICULO:");

        lblColor.setText("COLOR A ACTUALIZAR:");

        lblNumPuertas.setText("NUMERO DE PUERTAS:");

        lblTipoCaja.setText("TIPO DE CAJA:");

        cmbNumPuertas.setModel(new DefaultComboBoxModel(eNumPuertas.values()));
        cmbNumPuertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNumPuertasActionPerformed(evt);
            }
        });

        cmbTipoCaja.setModel(new DefaultComboBoxModel(eTipoCaja.values()));

        btnUpdate.setBackground(new java.awt.Color(204, 204, 255));
        btnUpdate.setText("ACTUALIZAR");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblNumPuertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipoCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTipoCaja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbNumPuertas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtColor)
                    .addComponent(txtPlaca))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPuertas)
                    .addComponent(cmbNumPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoCaja)
                    .addComponent(cmbTipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(0, 41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNumPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNumPuertasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNumPuertasActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(buscarVehiculo(this.txtPlaca.getText())>-1){
            updateVehiculo();
        }else{
            JOptionPane.showMessageDialog(this, 
                "OBJETO NO ENCONTRADO",
                "Información",
                JOptionPane.INFORMATION_MESSAGE);
        }
        limpiarCampos();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbNumPuertas;
    private javax.swing.JComboBox<String> cmbTipoCaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblNumPuertas;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTipoCaja;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
    
    public int buscarVehiculo(String placa) {
        int pos = -1;
        for (int i = 0; i < this.auxParqueadero.getLstVehiculos().size(); i++) {
            if (placa.equalsIgnoreCase(this.auxParqueadero.getLstVehiculos().get(i).getPlaca())) {
                pos = i;
                break;
            }
        }
        
        return pos;
    }
    public void updateVehiculo(){
        String placa = this.txtPlaca.getText();
        String color = this.txtColor.getText();
        int vehiculo = this.buscarVehiculo(placa);
        this.auxParqueadero.getLstVehiculos().get(vehiculo).setColor(color);
        this.auxParqueadero.getLstVehiculos().get(vehiculo).setNumPuertas((eNumPuertas)this.cmbNumPuertas.getSelectedItem());
        this.auxParqueadero.getLstVehiculos().get(vehiculo).setCaja((eTipoCaja)this.cmbTipoCaja.getSelectedItem());
        JOptionPane.showMessageDialog(this, 
                "¡ACTUALIZADO CON EXITO!",
                "Información",
                JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void limpiarCampos(){
        this.txtPlaca.setText("");
        this.txtColor.setText("");
        this.cmbNumPuertas.setSelectedIndex(0);
        this.cmbTipoCaja.setSelectedIndex(0);
    }
    
}
