/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author migue
 */
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.*;

public class JPanelAddVehiculo extends javax.swing.JPanel {

    private clsParqueadero auxParqueadero;
    
    public JPanelAddVehiculo(clsParqueadero objParqueadero) {
        this.auxParqueadero = objParqueadero;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitulo = new javax.swing.JLabel();
        jLblPlaca = new javax.swing.JLabel();
        jLblColor = new javax.swing.JLabel();
        jLblCilindraje = new javax.swing.JLabel();
        jLblNumPuertas = new javax.swing.JLabel();
        jLblTipoCaja = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        cmbNumPuertas = new javax.swing.JComboBox<>();
        cmbTipoCaja = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();

        jLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitulo.setText("AGREGAR VEHICULO");

        jLblPlaca.setText("PLACA:");

        jLblColor.setText("COLOR:");

        jLblCilindraje.setText("CILINDRAJE:");

        jLblNumPuertas.setText("NUMERO DE PUERTAS:");

        jLblTipoCaja.setText("TIPO DE CAJA:");

        cmbNumPuertas.setModel(new DefaultComboBoxModel(eNumPuertas.values()));

        cmbTipoCaja.setModel(new DefaultComboBoxModel(eTipoCaja.values()));

        btnRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLblNumPuertas)
                            .addComponent(jLblColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblTipoCaja, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCilindraje, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbNumPuertas, javax.swing.GroupLayout.Alignment.LEADING, 0, 115, Short.MAX_VALUE)
                            .addComponent(cmbTipoCaja, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCilindraje)
                            .addComponent(txtPlaca)
                            .addComponent(txtColor))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCilindraje)
                    .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNumPuertas)
                    .addComponent(cmbNumPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTipoCaja)
                    .addComponent(cmbTipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrarVehiculo();
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbNumPuertas;
    private javax.swing.JComboBox<String> cmbTipoCaja;
    private javax.swing.JLabel jLblCilindraje;
    private javax.swing.JLabel jLblColor;
    private javax.swing.JLabel jLblNumPuertas;
    private javax.swing.JLabel jLblPlaca;
    private javax.swing.JLabel jLblTipoCaja;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

    public void registrarVehiculo(){
        try {
            clsVehiculo objVehiculo = new clsVehiculo();
            objVehiculo.setPlaca(this.txtPlaca.getText());
            objVehiculo.setColor(this.txtColor.getText());
            objVehiculo.setCilindraje(this.txtCilindraje.getText());
            objVehiculo.setNumPuertas((eNumPuertas)this.cmbNumPuertas.getSelectedItem());
            objVehiculo.setCaja((eTipoCaja)this.cmbTipoCaja.getSelectedItem());

            this.auxParqueadero.agregarVehiculo(objVehiculo);
            JOptionPane.showMessageDialog(this,
                    "Vehiculo registrado con exito",
                    "Informacion",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this,
                    "Error, No hay espacio",
                    "Validar datos",
                    JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Error, dato mal digitado",
                    "Validar datos",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error",
                    "",
                    JOptionPane.ERROR_MESSAGE);
        }
        limpiarCampos();
    }
    
    public void limpiarCampos() {
        this.txtPlaca.setText("");
        this.txtColor.setText("");
        this.txtCilindraje.setText("");
        this.cmbNumPuertas.setSelectedIndex(0);
        this.cmbTipoCaja.setSelectedIndex(0);
    }
    
}
