/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Miguel A. Quevedo P.
 * @correo mquevedo@unicauca.edu.co
 * 
 */

public class JfLogin extends javax.swing.JFrame {

    private JPanelAddStudent panelAddStudent;
    private JPanelDepartments panelDepartments;
    private JPanelAddTeacher panelAddTeacher;
    private JPanelViewDictate panelViewDictate;
    private JPanelUpdateStudent panelUpdateStudent;
    private JPanelUpdateTeacher panelUpdateTeacher;
    private JPanelDltStudent panelDltStudent;
    private JPanelAddInfoCourse panelAddInfoCourse;
    private JPanelAddCourseStudent panelAddCourseStudent;
    private JPanelViewAvailabity panelViewAvailabity;
    private JPanelAttendance panelAttendance;
    private JPanelScore panelScore;
    private JPanelLogin panelLogin;
    private JPanelBtnAdmin pAdmin;
    
    public JfLogin() {
        this.panelAddStudent = new JPanelAddStudent();
        this.panelDepartments = new JPanelDepartments();
        this.panelAddTeacher = new JPanelAddTeacher();
        this.panelViewDictate = new JPanelViewDictate();
        this.panelUpdateStudent = new JPanelUpdateStudent();
        this.panelUpdateTeacher = new JPanelUpdateTeacher();
        this.panelDltStudent = new JPanelDltStudent();
        this.panelAddInfoCourse = new JPanelAddInfoCourse();
        this.panelAddCourseStudent = new JPanelAddCourseStudent();
        this.panelViewAvailabity = new JPanelViewAvailabity();
        this.panelAttendance = new JPanelAttendance();
        this.panelScore = new JPanelScore();
        this.panelLogin = new JPanelLogin();
        this.pAdmin = new JPanelBtnAdmin();
        initComponents();
        login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPBackground = new javax.swing.JPanel();
        pLeft = new javax.swing.JPanel();
        pCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRINCIPAL");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pLeft.setPreferredSize(new java.awt.Dimension(250, 500));

        javax.swing.GroupLayout pLeftLayout = new javax.swing.GroupLayout(pLeft);
        pLeft.setLayout(pLeftLayout);
        pLeftLayout.setHorizontalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        pLeftLayout.setVerticalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pCentralLayout = new javax.swing.GroupLayout(pCentral);
        pCentral.setLayout(pCentralLayout);
        pCentralLayout.setHorizontalGroup(
            pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        pCentralLayout.setVerticalGroup(
            pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPBackgroundLayout = new javax.swing.GroupLayout(jPBackground);
        jPBackground.setLayout(jPBackgroundLayout);
        jPBackgroundLayout.setHorizontalGroup(
            jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackgroundLayout.createSequentialGroup()
                .addComponent(pLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPBackgroundLayout.setVerticalGroup(
            jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfLogin().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPBackground;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel pCentral;
    private javax.swing.JPanel pLeft;
    // End of variables declaration//GEN-END:variables

    public void addStudent(){
        panelAddStudent.setSize(700, 300);
        panelAddStudent.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelAddStudent, BorderLayout.CENTER);
        drawCentral();
    }
    public void addTeacher(){
        panelAddTeacher.setSize(700, 300);
        panelAddTeacher.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelAddTeacher, BorderLayout.CENTER);
        drawCentral();
    }
    public void viewDictate(){
        panelViewDictate.setSize(700, 300);
        panelViewDictate.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelViewDictate, BorderLayout.CENTER);
        drawCentral();
    }
    public void viewDepartments(){
        panelDepartments.setSize(700, 300);
        panelDepartments.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelDepartments, BorderLayout.CENTER);
        drawCentral();
    }
    public void updateStudent(){
        panelUpdateStudent.setSize(700, 500);
        panelUpdateStudent.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelUpdateStudent, BorderLayout.CENTER);
        drawCentral();
    }
    public void updateTeacher(){
        panelUpdateTeacher.setSize(700, 500);
        panelUpdateTeacher.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelUpdateTeacher, BorderLayout.CENTER);
        drawCentral();
    }
    public void dltStudent(){
        panelDltStudent.setSize(700, 500);
        panelDltStudent.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelDltStudent, BorderLayout.CENTER);
        drawCentral();
    }
    
    public void addInfoCourse(){
        panelAddInfoCourse.setSize(700, 500);
        panelAddInfoCourse.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelAddInfoCourse, BorderLayout.CENTER);
        drawCentral();
    }
    
    public void addCourseStudent(){
        panelAddCourseStudent.setSize(700, 500);
        panelAddCourseStudent.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelAddCourseStudent, BorderLayout.CENTER);
        drawCentral();
    }
    
    public void viewAvailabity(){
        panelViewAvailabity.setSize(700, 500);
        panelViewAvailabity.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelViewAvailabity, BorderLayout.CENTER);
        drawCentral();
    }
    
    public void attendance(){
        panelAttendance.setSize(700, 500);
        panelAttendance.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelAttendance, BorderLayout.CENTER);
        drawCentral();
    }
    
    public void score(){
        panelScore.setSize(700, 500);
        panelScore.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelScore, BorderLayout.CENTER);
        drawCentral();
    }
    
    public void login(){
        panelLogin.setSize(900, 500);
        panelLogin.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(panelLogin, BorderLayout.CENTER);
        drawCentral();
    }
    
    public void pAdmin(){
        pAdmin.setSize(900, 500);
        pAdmin.setLocation(0, 0);
        this.pCentral.removeAll();
        this.pCentral.add(pAdmin, BorderLayout.CENTER);
        drawCentral();
    }
    
    public void drawCentral(){
		this.pCentral.revalidate();
		this.pCentral.repaint();
    }
}
