/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import access.clsDepartmentAccess;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.clsDepartment;

/**
 *
 * @author Miguel A. Quevedo P.
 * @correo mquevedo@unicauca.edu.co
 * 
 */

public class JPanelDepartments extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDepartments
     */
    private clsDepartment auxDepartment;
    private clsDepartmentAccess auxDepartmentAccess;
    private List<clsDepartment> lstDepartments;
    
    public JPanelDepartments() {
        initComponents();
        auxDepartmentAccess = new clsDepartmentAccess();
        lstDepartments = new ArrayList<>();
        cargarTablaVehiculo();
    }

    public void cargarTablaVehiculo() {

        this.lstDepartments = this.auxDepartmentAccess.watchDepartments();
        
        DefaultTableModel matriz = (DefaultTableModel) tDeparment.getModel();
        matriz.setRowCount(0);
        for (int i = 0; i < this.lstDepartments.size(); i++) {
            matriz.addRow(new Object[]{
                this.lstDepartments.get(i).getName(),
                this.lstDepartments.get(i).getJefe(),
            });
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tDeparment = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tDeparment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NOMBRE", "JEFE"
            }
        ));
        tDeparment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tDeparment);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 688, 288));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tDeparment;
    // End of variables declaration//GEN-END:variables

    

    
}
