package Vista;

import Modelo.Pokemon;
import java.util.ArrayList;

/**
 *
 * @author Acer
 */
public class MiVentana extends javax.swing.JFrame {

    /** Creates new form MiVentana */
    public MiVentana() {
         initComponents();   
         inicializarComponentes();
    }
    public void inicializarComponentes (){
        listaPokemonesAll = new ArrayList<>();
        panelAgregarPokemon = new PanelAgregarPokemon(listaPokemonesAll);
        panelEditarPokemon  = new PanelEditarPokemon(listaPokemonesAll); 
        panelListarPokemon  = new PanelListarPokemon(listaPokemonesAll);
        panelBorrarPokemon  = new PanelBorrarPokemon(listaPokemonesAll);  
        panelGestionarRegion = new PanelGestionarRegion();
        panelGestionarPueblo = new PanelGestionarPueblo();        
    } 


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        POKEDEX = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        Opciones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        lblRegiones = new javax.swing.JLabel();
        lblPueblos = new javax.swing.JLabel();
        btnGestionRegion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelResultados = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        POKEDEX.setBackground(new java.awt.Color(51, 51, 255));
        POKEDEX.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 51, 51));
        lblTitulo.setFont(new java.awt.Font("Goudy Stout", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 0));
        lblTitulo.setText("POKEDEX");
        POKEDEX.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 420, 40));

        getContentPane().add(POKEDEX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 110));

        Opciones.setBackground(new java.awt.Color(255, 51, 0));
        Opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(51, 204, 255));
        btnAgregar.setFont(new java.awt.Font("Snap ITC", 2, 12)); // NOI18N
        btnAgregar.setText("Agregar Pokemon");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irPanelAgregar(evt);
            }
        });
        Opciones.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        btnEditar.setBackground(new java.awt.Color(51, 204, 255));
        btnEditar.setFont(new java.awt.Font("Snap ITC", 2, 12)); // NOI18N
        btnEditar.setText("Editar Pokemon");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irPanelEditar(evt);
            }
        });
        Opciones.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 150, -1));

        btnListar.setBackground(new java.awt.Color(51, 204, 255));
        btnListar.setFont(new java.awt.Font("Snap ITC", 2, 11)); // NOI18N
        btnListar.setText("Listar Pokemon");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irPanelListar(evt);
            }
        });
        Opciones.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, -1));

        btnBorrar.setBackground(new java.awt.Color(51, 204, 255));
        btnBorrar.setFont(new java.awt.Font("Snap ITC", 2, 12)); // NOI18N
        btnBorrar.setText("Borrar Pokemon");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irPanelBorrar(evt);
            }
        });
        Opciones.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, -1));

        lblRegiones.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        lblRegiones.setText("GESTIONAR REGIONES");
        Opciones.add(lblRegiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 60));

        lblPueblos.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        lblPueblos.setText("GESTIONAR PUEBLOS");
        Opciones.add(lblPueblos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 30));

        btnGestionRegion.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        btnGestionRegion.setForeground(new java.awt.Color(204, 0, 204));
        btnGestionRegion.setText("Region");
        btnGestionRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irPanelGestionarRegion(evt);
            }
        });
        Opciones.add(btnGestionRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, -1));

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 204));
        jButton2.setText("Pueblo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irPanelGestionarPueblo(evt);
            }
        });
        Opciones.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 100, -1));

        getContentPane().add(Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 280, 480));

        panelResultados.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(panelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 780, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irPanelEditar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irPanelEditar
        this.panelResultados.remove(panelListarPokemon); 
        this.panelResultados.remove(panelBorrarPokemon); 
        this.panelResultados.remove(panelAgregarPokemon);
        this.panelResultados.remove(panelGestionarRegion);
        this.panelResultados.remove(panelGestionarPueblo);
        this.panelResultados.add(panelEditarPokemon);        // TODO add your handling code here:
        dibujar();  
    }//GEN-LAST:event_irPanelEditar

    private void irPanelBorrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irPanelBorrar
        this.panelResultados.remove(panelListarPokemon); 
        this.panelResultados.remove(panelEditarPokemon); 
        this.panelResultados.remove(panelAgregarPokemon);
        this.panelResultados.remove(panelGestionarRegion);
        this.panelResultados.remove(panelGestionarPueblo); 
        this.panelResultados.add(panelBorrarPokemon);        // TODO add your handling code here:
        dibujar();  
    }//GEN-LAST:event_irPanelBorrar

    private void irPanelAgregar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irPanelAgregar
        this.panelResultados.remove(panelListarPokemon); 
        this.panelResultados.remove(panelBorrarPokemon); 
        this.panelResultados.remove(panelEditarPokemon);
        this.panelResultados.remove(panelGestionarRegion);
        this.panelResultados.remove(panelGestionarPueblo); 
        this.panelResultados.add(panelAgregarPokemon);        // TODO add your handling code here:
        dibujar();        
    }//GEN-LAST:event_irPanelAgregar

    private void irPanelListar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irPanelListar
        this.panelResultados.remove(panelBorrarPokemon); 
        this.panelResultados.remove(panelEditarPokemon); 
        this.panelResultados.remove(panelAgregarPokemon); 
        this.panelResultados.remove(panelGestionarRegion);
        this.panelResultados.remove(panelGestionarPueblo); 
        this.panelResultados.add(panelListarPokemon);        // TODO add your handling code here:
        dibujar();      
    }//GEN-LAST:event_irPanelListar

    private void irPanelGestionarRegion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irPanelGestionarRegion
        this.panelResultados.remove(panelListarPokemon);         
        this.panelResultados.remove(panelBorrarPokemon); 
        this.panelResultados.remove(panelEditarPokemon); 
        this.panelResultados.remove(panelAgregarPokemon); 
        this.panelResultados.remove(panelGestionarPueblo); 
        this.panelResultados.add(panelGestionarRegion);        // TODO add your handling code here:
        dibujar(); 
    }//GEN-LAST:event_irPanelGestionarRegion

    private void irPanelGestionarPueblo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irPanelGestionarPueblo
        this.panelResultados.remove(panelListarPokemon);         
        this.panelResultados.remove(panelBorrarPokemon); 
        this.panelResultados.remove(panelEditarPokemon); 
        this.panelResultados.remove(panelAgregarPokemon); 
        this.panelResultados.remove(panelGestionarRegion);
        this.panelResultados.add(panelGestionarPueblo);        // TODO add your handling code here:
        dibujar(); 
    }//GEN-LAST:event_irPanelGestionarPueblo

    private void dibujar(){
        this.panelResultados.revalidate();
        this.panelResultados.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Opciones;
    private javax.swing.JPanel POKEDEX;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGestionRegion;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblPueblos;
    private javax.swing.JLabel lblRegiones;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelResultados;
    // End of variables declaration//GEN-END:variables
    private PanelAgregarPokemon panelAgregarPokemon;
    private PanelEditarPokemon panelEditarPokemon; 
    private PanelListarPokemon panelListarPokemon;
    private PanelBorrarPokemon panelBorrarPokemon; 
    private PanelGestionarRegion panelGestionarRegion;
    private PanelGestionarPueblo panelGestionarPueblo;
    private ArrayList<Pokemon> listaPokemonesAll;
}
