/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.Agua;
import Modelo.Arcanine;
import Modelo.Bulbasur;
import Modelo.Charmander;
import Modelo.Entrenador;
import Modelo.Fuego;
import Modelo.Ninetales;
import Modelo.Planta;
import Modelo.Pokemon;
import Modelo.Psyduck;
import Modelo.Region;
import Modelo.Squirtle;
import Modelo.Vaporeon;
import Modelo.Victreebel;
import Modelo.Vileplume;
import Modelo.eGenero;
import Modelo.eRegion;
import Modelo.eTipo;
import Modelo.eNombre;
import javax.swing.DefaultComboBoxModel;
import java.util.ArrayList;
import java.text.ParseException;
import java.util.Collection;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.lang.String;
import java.lang.NumberFormatException;
/**
 *
 * @author Acer
 */
public class PanelAgregarPokemon extends javax.swing.JPanel {

    /**
     * Creates new form PanelAgregarPokemon
     */
    public PanelAgregarPokemon(ArrayList<Pokemon>listaP) {
        initComponents();
        inicializarComponentes(listaP);
    }
    private void inicializarComponentes(ArrayList<Pokemon>listaP){
        this.listaPokemones = listaP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblDebilidad = new javax.swing.JLabel();
        lblFortaleza = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        lblTituloAgregar = new javax.swing.JLabel();
        btnRegistrarPokemon = new javax.swing.JButton();
        cGeneroPokemon = new javax.swing.JComboBox<>();
        cDebilidadPokemon = new javax.swing.JComboBox<>();
        cFortalezaPokemon = new javax.swing.JComboBox<>();
        cNombrePokemon = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setText("Nombre");

        lblDescripcion.setText("Descripción");

        lblPeso.setText("Peso");

        lblAltura.setText("Altura");

        lblGenero.setText("Género");

        lblNumero.setText("Número");

        lblDebilidad.setText("Debilidad");

        lblFortaleza.setText("Fortaleza");

        lblNivel.setText("Nivel");

        lblTituloAgregar.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        lblTituloAgregar.setText("AGREGAR POKEMON");

        btnRegistrarPokemon.setText("Registrar Pokemon");
        btnRegistrarPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPokemon(evt);
            }
        });

        cGeneroPokemon.setModel(new DefaultComboBoxModel(eGenero.values())
        );

        cDebilidadPokemon.setModel(new DefaultComboBoxModel(eTipo.values()));

        cFortalezaPokemon.setModel(new DefaultComboBoxModel(eTipo.values()));

        cNombrePokemon.setModel(new DefaultComboBoxModel(eNombre.values()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTituloAgregar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrarPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblDescripcion)
                            .addComponent(lblPeso)
                            .addComponent(lblAltura)
                            .addComponent(lblGenero)
                            .addComponent(lblNumero)
                            .addComponent(lblDebilidad)
                            .addComponent(lblFortaleza)
                            .addComponent(lblNivel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cGeneroPokemon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cDebilidadPokemon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cFortalezaPokemon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cNombrePokemon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(cNombrePokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(cGeneroPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cDebilidadPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDebilidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cFortalezaPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFortaleza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivel)
                    .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarPokemon)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarPokemon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPokemon

        eNombre nombrePokemon,opcPokemon;
        String descripcionPokemon;
        double pesoPokemon = 0;
        double alturaPokemon = 0;
        eGenero genero;
        int numeroPokemon;
        eTipo debilidad;
        eTipo fortaleza;
        int nivelPokemon;
        nombrePokemon = (eNombre) cNombrePokemon.getSelectedItem();
        opcPokemon=nombrePokemon;
        genero=(eGenero) cGeneroPokemon.getSelectedItem();
        debilidad=(eTipo) cDebilidadPokemon.getSelectedItem();
        fortaleza=(eTipo) cFortalezaPokemon.getSelectedItem();
        
        try{
        descripcionPokemon = this.txtDescripcion.getText();  
        pesoPokemon = Double.parseDouble(this.txtPeso.getText());
        alturaPokemon = Double.parseDouble(this.txtAltura.getText());
        nivelPokemon = Integer.parseInt(this.txtNivel.getText());
        numeroPokemon = Integer.parseInt(this.txtNumero.getText()); 
       
        if(descripcionPokemon.equals("")){
            JOptionPane.showMessageDialog(this, "por favor ingrese descripcion del pokemon");       
        }
        else{
        JOptionPane.showMessageDialog(this, "Pokemon registrado correctamente");
        Modelo.Pokemon.encontrarPokemon(opcPokemon, descripcionPokemon, pesoPokemon, alturaPokemon, genero, numeroPokemon, debilidad, fortaleza, nivelPokemon);
        listaPokemones.add(Modelo.Pokemon.encontrarPokemon(nombrePokemon,descripcionPokemon, pesoPokemon, alturaPokemon,genero, numeroPokemon, debilidad, fortaleza, nivelPokemon));       
        }
        }catch(NumberFormatException exception){
            JOptionPane.showMessageDialog(this, "Ingrese valores numericos donde se solicitan");
            
        } 
        limpiarFormulario();


    }//GEN-LAST:event_RegistrarPokemon
    private void limpiarFormulario(){
        cNombrePokemon.setActionCommand("");
        cGeneroPokemon.setActionCommand("");
        cDebilidadPokemon.setActionCommand("");
        cFortalezaPokemon.setActionCommand("");
        this.txtDescripcion.setText("");
        this.txtPeso.setText("");
        this.txtAltura.setText("");
        this.txtNivel.setText("");
        this.txtNumero.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPokemon;
    private javax.swing.JComboBox<String> cDebilidadPokemon;
    private javax.swing.JComboBox<String> cFortalezaPokemon;
    private javax.swing.JComboBox<String> cGeneroPokemon;
    private javax.swing.JComboBox<String> cNombrePokemon;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblDebilidad;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFortaleza;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTituloAgregar;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
    ArrayList<Pokemon> listaPokemones;

       // TODO add your handling code here:
//        eNombre nombrePokemon,opcPokemon;
//        String descripcionPokemon;
//        
//        double pesoPokemon;
//        double alturaPokemon;
//        
//        eGenero genero;
//        int numeroPokemon;
//        eTipo debilidad;
//        eTipo fortaleza;
//        int nivelPokemon;
////        try{
//        nombrePokemon = (eNombre) cNombrePokemon.getSelectedItem();
//        opcPokemon=nombrePokemon;
//
// //       nombrePokemon = nombresPokemon.getName();
//        descripcionPokemon = this.txtDescripcion.getText();  
////        if(nombrePokemon.equals("")){
////            JOptionPane.showMessageDialog(this, "por favor ingrese nombre del pokemon");       
////        }
////        else if(descripcionPokemon.equals("")){
////            JOptionPane.showMessageDialog(this, "por favor ingrese descripcion del pokemon");       
////        }
////        else{
////        
////        }
//        pesoPokemon = Double.parseDouble(this.txtPeso.getText());
//        alturaPokemon = Double.parseDouble(this.txtAltura.getText());
//        nivelPokemon = Integer.parseInt(this.txtNivel.getText());
//        numeroPokemon = Integer.parseInt(this.txtNumero.getText()); 
//        genero=(eGenero) cGeneroPokemon.getSelectedItem();
//        debilidad=(eTipo) cDebilidadPokemon.getSelectedItem();
//        fortaleza=(eTipo) cFortalezaPokemon.getSelectedItem();
//
//        //traer objPokemon
//        Modelo.Pokemon.encontrarPokemon(opcPokemon, descripcionPokemon, pesoPokemon, alturaPokemon, genero, numeroPokemon, debilidad, fortaleza, nivelPokemon);
////        encontrarPokemon(nombrePokemon,descripcionPokemon, pesoPokemon,alturaPokemon,genero, numeroPokemon, debilidad, fortaleza, nivelPokemon);
//        listaPokemones.add(Modelo.Pokemon.encontrarPokemon(nombrePokemon,descripcionPokemon, pesoPokemon, alturaPokemon,genero, numeroPokemon, debilidad, fortaleza, nivelPokemon));
//
//                for(int i =0 ;i<listaPokemones.size() ; i++ ){
//
//                    System.out.println("p "+listaPokemones.get(i).getNombrePokemon());
//                    System.out.println("p "+listaPokemones.get(i).getDescripcionPokemon());
//            
//        }  
//        
////        JOptionPane.showMessageDialog(this, "Pokemon regisrado correctamente");
////        }catch(NumberFormatException excepcion){
////        JOptionPane.showMessageDialog(this, "el peso debe ser un valor numerico");            
////        }
//               // TODO add your handling code here:   
    
    
}
