/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Region;
import java.util.ArrayList;

/**
 *
 * @author Acer
 */
public class PanelGestionarRegion extends javax.swing.JPanel {
    ArrayList<Region> listaRegion = new ArrayList<Region>();
    /**
     * Creates new form PanelGestionarRegion
     */
    public PanelGestionarRegion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreRegion = new javax.swing.JLabel();
        lblDescripcionRegion = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtNombreRegion = new javax.swing.JTextField();
        txtDescripcionRegion = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnRegistrarRegion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegion = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 204, 102));

        lblNombreRegion.setText("NombreRegion");

        lblDescripcionRegion.setText("Descripcion region");

        lblCodigo.setText("Codigo");

        btnRegistrarRegion.setText("Gestionar");
        btnRegistrarRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarRegionP(evt);
            }
        });

        jTableRegion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Codigo"
            }
        ));
        jScrollPane1.setViewportView(jTableRegion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescripcionRegion)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreRegion, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreRegion, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtDescripcionRegion)
                            .addComponent(txtCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarRegion)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRegion)
                    .addComponent(txtNombreRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcionRegion)
                    .addComponent(txtDescripcionRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarRegion))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registarRegionP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarRegionP
        Region region = new Region(txtNombreRegion.getText(),txtDescripcionRegion.getText(),txtCodigo.getText());
        listaRegion.add(region);
        listarRegion();
        txtNombreRegion.setText("");
        txtDescripcionRegion.setText("");
        txtCodigo.setText("");
    }//GEN-LAST:event_registarRegionP
    
    public void listarRegion( ) {
        String matriz[][] = new String[listaRegion.size()][3];
        for(int i =0 ;i<listaRegion.size() ; i++ ){
            matriz[i][0] = listaRegion.get(i).getNombreRegion();
            matriz[i][1] = listaRegion.get(i).getDerscripcionRegion();
            matriz[i][2] = listaRegion.get(i).getCodigoRegion();
        }        
        jTableRegion.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
            new String [] {
                "Nombre", "Descripcion", "Codigo"
            }
        ));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarRegion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRegion;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcionRegion;
    private javax.swing.JLabel lblNombreRegion;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcionRegion;
    private javax.swing.JTextField txtNombreRegion;
    // End of variables declaration//GEN-END:variables
}
