/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Pokemon;
import Modelo.eGenero;
import Modelo.eNombre;
import Modelo.eTipo;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;


/**
 *
 * @author Acer
 */
public class PanelBorrarPokemon extends javax.swing.JPanel {
     private ArrayList<Pokemon> listaPokemones;
    /**
     * Creates new form PanelBorrarPokemon
     */
    public PanelBorrarPokemon(ArrayList<Pokemon>listaP) {
        initComponents();      
        inicializarComponentes(listaP);

    }
        private void inicializarComponentes(ArrayList<Pokemon>listaP){
        this.listaPokemones = listaP;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePokemonBorrar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblOpcionPokemon = new javax.swing.JLabel();
        txtOpcionPokemonBorrar = new javax.swing.JTextField();
        btnListaPborrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTablePokemonBorrar.setModel(new javax.swing.table.DefaultTableModel(new Object[0][2],new String[]{"Numero","Nombre"}));
        jScrollPane1.setViewportView(jTablePokemonBorrar);

        jButton1.setText("BORRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPokemonElegido(evt);
            }
        });

        lblOpcionPokemon.setText("Ingrese el numero del pokemon");

        btnListaPborrar.setText("Listar Pokemones");
        btnListaPborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPokemonesB(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOpcionPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtOpcionPokemonBorrar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnListaPborrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnListaPborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lblOpcionPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtOpcionPokemonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void borrarPokemonElegido(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPokemonElegido
        int numeroPokemonB = 0;
        try{
            numeroPokemonB = Integer.parseInt(this.txtOpcionPokemonBorrar.getText());
        }catch(NumberFormatException exception){
            JOptionPane.showMessageDialog(this, "El número de pokemon debe ser un valor numérico");
        }
        for(int i =0 ;i<listaPokemones.size() ; i++ ){
            if(numeroPokemonB == listaPokemones.get(i).getNumeroPokemon()){
                this.listaPokemones.remove(i);  
                JOptionPane.showMessageDialog(this, "Pokemon eliminado exitosamente");
            }  
        }
        
        limpiarCasilla();
   
    }//GEN-LAST:event_borrarPokemonElegido

    private void listarPokemonesB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPokemonesB
        Object matriz[][] = new Object[listaPokemones.size()][2];
        for(int i =0 ;i<listaPokemones.size() ; i++ ){
            matriz[i][0] = listaPokemones.get(i).getNumeroPokemon();
            matriz[i][1] = listaPokemones.get(i).getNombrePokemon();
 
        }   
        
        jTablePokemonBorrar.setModel(new javax.swing.table.DefaultTableModel(
        matriz,        
        new String[]{
            "Numero","Nombre"
        }
        ));
            
    }//GEN-LAST:event_listarPokemonesB

    private void limpiarCasilla(){
            this.txtOpcionPokemonBorrar.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListaPborrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePokemonBorrar;
    private javax.swing.JLabel lblOpcionPokemon;
    private javax.swing.JTextField txtOpcionPokemonBorrar;
    // End of variables declaration//GEN-END:variables
}
