/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Pokemon;
import java.awt.event.ActionEvent;
import java.util.ArrayList;

/**
 *
 * @author Acer
 */
public class PanelListarPokemon extends javax.swing.JPanel {

    private ArrayList<Pokemon> listaPokemones;

    /**
     * Creates new form PanelListarPokemon
     */
    public PanelListarPokemon(ArrayList<Pokemon>listaP) {
        initComponents();
        inicializarComponentes(listaP);
    }
    private void inicializarComponentes(ArrayList<Pokemon>listaP){
        this.listaPokemones = listaP;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaPokemones = new javax.swing.JTable();
        btnCargarDatosP = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableListaPokemones.setModel(new javax.swing.table.DefaultTableModel(new Object[0][9],new String[]{"Nombre","Descripcion","Peso","Altura","Genero","Numero","Debilidad","Fortaleza","nivel"}));
        jScrollPane1.setViewportView(jTableListaPokemones);

        btnCargarDatosP.setText("Cargar datos");
        btnCargarDatosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDatosPokemon(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addComponent(btnCargarDatosP)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCargarDatosP)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatosPokemon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDatosPokemon
//        Object matriz[][] = new Object[this.listaPokemones.size()][9];
//        int i=0;
        Object matriz[][] = new Object[listaPokemones.size()][9];
        for(int i =0 ;i<listaPokemones.size() ; i++ ){
            matriz[i][0] = listaPokemones.get(i).getNombrePokemon();
            matriz[i][1] = listaPokemones.get(i).getDescripcionPokemon();
            matriz[i][2] = listaPokemones.get(i).getPesoPokemon();
            matriz[i][3] = listaPokemones.get(i).getAlturaPokemon();
            matriz[i][4] = listaPokemones.get(i).getGenero();
            matriz[i][5] = listaPokemones.get(i).getNumeroPokemon();
            matriz[i][6] = listaPokemones.get(i).getDebilidad();
            matriz[i][7] = listaPokemones.get(i).getFortaleza();
            matriz[i][8] = listaPokemones.get(i).getNivelPokemon();     
        }   
        
        jTableListaPokemones.setModel(new javax.swing.table.DefaultTableModel(
        matriz,        
        new String[]{
            "Nombre","Descripcion","Peso","Altura","Genero","Numero","Debilidad","Fortaleza","nivel"
        }
        ));
               

    }//GEN-LAST:event_cargarDatosPokemon
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarDatosP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaPokemones;
    // End of variables declaration//GEN-END:variables

}
