/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import access.clsStudentAccess;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.clsStudent;

/**
 *
 * @author Miguel A. Quevedo P.
 * @correo mquevedo@unicauca.edu.co
 * 
 */

public class JPanelAddStudent extends javax.swing.JPanel {

    /**
     * Creates new form JPanelAddStudent
     */
    private clsStudentAccess auxStudent;
    public JPanelAddStudent() {
        this.auxStudent = new clsStudentAccess();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblDateBirth = new javax.swing.JLabel();
        lblTypeDoc = new javax.swing.JLabel();
        lblNumDoc = new javax.swing.JLabel();
        lblCodeStudent = new javax.swing.JLabel();
        lblCareer = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNumDoc = new javax.swing.JTextField();
        txtCodeStudent = new javax.swing.JTextField();
        dateBirth = new com.toedter.calendar.JDateChooser();
        cmbTypeDoc = new javax.swing.JComboBox<>();
        cmbCareer = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JToggleButton();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();

        lblName.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblName.setText("NOMBRE:");

        lblDateBirth.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblDateBirth.setText("FECHA DE NACIMIENTO:");

        lblTypeDoc.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblTypeDoc.setText("TIPO DE DOCUMENTO:");

        lblNumDoc.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblNumDoc.setText("NUMERO DE DOCUMENTO:");

        lblCodeStudent.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCodeStudent.setText("CODIGO DE ESTUDIANTE:");

        lblCareer.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCareer.setText("CARRERA:");

        cmbTypeDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta de identidad", "Cedula de ciudadania", "Cedula de extranjeria", "Pasaporte" }));

        cmbCareer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artes Plásticas", "Diseño Gráfico", "Dirección de Banda", "Licenciatura en Música", "Música Instrumental", "Ingeniería Agroindustrial", "Ingeniería Agropecuaria", "Ingeniería Forestal", "Tecnología Agroindustrial", "Enfermería", "Fisioterapia", "Fonoaudiología", "Medicina", "Administración de Empresas", "Contaduría Pública", "Economía", "Turismo", "Antropología", "Filosofía", "Geografía del Desarrollo Regional y Ambiental", "Historia", "Licenciatura en Lenguas Modernas con Énfasis en Inglés y Francés", "Licenciatura en Etnoeducación", "Licenciatura en Lingüística y Semiótica", "Licenciatura en Literatura y Lengua Castellana", "Biología", "Ingeniería Física", "Licenciatura en Ciencias Naturales y Educación Ambiental", "Licenciatura en Educación Artística", "Licenciatura en Educación Básica Primaria", "Licenciatura en Educación Física, Recreación y Deportes", "Licenciatura en Matemáticas", "Matemáticas", "Química", "Tecnología en Gestión Ambiental", "Ciencia Política", "Comunicación Social", "Derecho", "Arquitectura", "Ingeniería Civil", "Ingeniería Ambiental", "Geotecnología", "Ingeniería Electrónica y Telecomunicaciones", "Ingeniería de Sistemas", "Ingeniería en Automática Industrial", "Tecnología en Telemática" }));

        btnAgregar.setBackground(new java.awt.Color(132, 244, 217));
        btnAgregar.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblEmail.setText("EMAIL:");

        lblPassword.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblPassword.setText("CONTRASEÑA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(145, 145, 145)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDateBirth)
                                    .addGap(45, 45, 45)
                                    .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTypeDoc)
                                        .addComponent(lblNumDoc)
                                        .addComponent(lblCodeStudent)
                                        .addComponent(lblCareer)
                                        .addComponent(lblEmail)
                                        .addComponent(lblPassword))
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNumDoc)
                                        .addComponent(cmbTypeDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCodeStudent)
                                        .addComponent(cmbCareer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEmail)
                                        .addComponent(txtPassword)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateBirth)
                    .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTypeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTypeDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodeStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCareer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        addStudent();
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregar;
    private javax.swing.JComboBox<String> cmbCareer;
    private javax.swing.JComboBox<String> cmbTypeDoc;
    private com.toedter.calendar.JDateChooser dateBirth;
    private javax.swing.JLabel lblCareer;
    private javax.swing.JLabel lblCodeStudent;
    private javax.swing.JLabel lblDateBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumDoc;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTypeDoc;
    private javax.swing.JTextField txtCodeStudent;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

    public void addStudent(){
        try{
		clsStudent objStudent = new clsStudent();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            //String strDate = formato.format(objStudent.getDateBirth().getTime());
            
		objStudent.setName(this.txtName.getText());
            objStudent.setDateBirth(formato.format(this.dateBirth.getCalendar().getTime()));
            objStudent.setTypeDocument(this.cmbTypeDoc.getSelectedItem().toString());
            objStudent.setNumDocument(Long.parseLong(this.txtNumDoc.getText()));
            objStudent.setCodeStudent(Long.parseLong(this.txtCodeStudent.getText()));
            objStudent.setCareer(this.cmbCareer.getSelectedItem().toString());
            objStudent.setEmail(this.txtEmail.getText());
            objStudent.setPassword(this.txtPassword.getText());
            
		this.auxStudent.AddStudent(objStudent);
            
		JOptionPane.showMessageDialog(this, 
				"Estudiante registrado con �xito",
				"Informacion",
				JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
		}
		catch(NullPointerException e){
			JOptionPane.showMessageDialog(this,
					"Error, No hay espacio",
					"Validar datos",
					JOptionPane.ERROR_MESSAGE);
		}
		catch(NumberFormatException e){
			JOptionPane.showMessageDialog(this,
					"Error, dato mal digitado",
					"Validar datos",
					JOptionPane.ERROR_MESSAGE);
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(this,
					"Error",
					"",
					JOptionPane.ERROR_MESSAGE);
		}
    }
    
    public void limpiarCampos() {
        this.txtName.setText("");
        this.dateBirth.setCalendar(null);
        this.txtCodeStudent.setText("");
        this.txtNumDoc.setText("");
        this.cmbCareer.setSelectedIndex(0);
        this.cmbTypeDoc.setSelectedIndex(0);
        this.txtEmail.setText("");
        this.txtPassword.setText("");
    }
}
