/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author migue
 */
public class JPanelBtnAdmin extends javax.swing.JPanel {

    private JPanelAddStudent panelAddStudent;
    private JPanelDepartments panelDepartments;
    private JPanelAddTeacher panelAddTeacher;
    private JPanelViewDictate panelViewDictate;
    private JPanelUpdateStudent panelUpdateStudent;
    private JPanelUpdateTeacher panelUpdateTeacher;
    private JPanelDltStudent panelDltStudent;
    private JPanelAddInfoCourse panelAddInfoCourse;
    private JPanelAddCourseStudent panelAddCourseStudent;
    private JPanelViewAvailabity panelViewAvailabity;
    private JPanelAttendance panelAttendance;
    private JPanelScore panelScore;
    private JPanelLogin panelLogin;
    private JFramePrincipal fMain;
    public JPanelBtnAdmin() {
        this.panelAddStudent = new JPanelAddStudent();
        this.panelDepartments = new JPanelDepartments();
        this.panelAddTeacher = new JPanelAddTeacher();
        this.panelViewDictate = new JPanelViewDictate();
        this.panelUpdateStudent = new JPanelUpdateStudent();
        this.panelUpdateTeacher = new JPanelUpdateTeacher();
        this.panelDltStudent = new JPanelDltStudent();
        this.panelAddInfoCourse = new JPanelAddInfoCourse();
        this.panelAddCourseStudent = new JPanelAddCourseStudent();
        this.panelViewAvailabity = new JPanelViewAvailabity();
        this.panelAttendance = new JPanelAttendance();
        this.panelScore = new JPanelScore();
        this.panelLogin = new JPanelLogin();
        this.fMain = new JFramePrincipal();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUpdateStudent = new javax.swing.JToggleButton();
        btnUpdateTeacher = new javax.swing.JToggleButton();
        btnAddCourse = new javax.swing.JToggleButton();
        btnViewDictate = new javax.swing.JToggleButton();
        btnViewAvailabity = new javax.swing.JToggleButton();
        btnScore = new javax.swing.JToggleButton();
        btnAttendance = new javax.swing.JToggleButton();
        btnDltStudent = new javax.swing.JToggleButton();
        btnDepartments = new javax.swing.JToggleButton();
        btnCourseStudent = new javax.swing.JToggleButton();
        btnAddStudent = new javax.swing.JButton();
        btnAddTeacher = new javax.swing.JButton();

        btnUpdateStudent.setBackground(new java.awt.Color(132, 244, 217));
        btnUpdateStudent.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnUpdateStudent.setText("ACTUALIZAR ESTUDIANTE");
        btnUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudentActionPerformed(evt);
            }
        });

        btnUpdateTeacher.setBackground(new java.awt.Color(132, 244, 217));
        btnUpdateTeacher.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnUpdateTeacher.setText("ACTUALIZAR DOCENTE");
        btnUpdateTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTeacherActionPerformed(evt);
            }
        });

        btnAddCourse.setBackground(new java.awt.Color(132, 244, 217));
        btnAddCourse.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAddCourse.setText("AGREGAR ASIGNATURA");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        btnViewDictate.setBackground(new java.awt.Color(132, 244, 217));
        btnViewDictate.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnViewDictate.setText("MATERIAS A DICTAR");
        btnViewDictate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDictateActionPerformed(evt);
            }
        });

        btnViewAvailabity.setBackground(new java.awt.Color(132, 244, 217));
        btnViewAvailabity.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnViewAvailabity.setText("INFORMACION ASIGNATURAS");
        btnViewAvailabity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAvailabityActionPerformed(evt);
            }
        });

        btnScore.setBackground(new java.awt.Color(132, 244, 217));
        btnScore.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnScore.setText("CALIFICAR ESTUDIANTE");
        btnScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoreActionPerformed(evt);
            }
        });

        btnAttendance.setBackground(new java.awt.Color(132, 244, 217));
        btnAttendance.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAttendance.setText("ASIGNAR FALTAS");
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });

        btnDltStudent.setBackground(new java.awt.Color(132, 244, 217));
        btnDltStudent.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnDltStudent.setText("INHABILITAR ESTUDIANTE");
        btnDltStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDltStudentActionPerformed(evt);
            }
        });

        btnDepartments.setBackground(new java.awt.Color(132, 244, 217));
        btnDepartments.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnDepartments.setText("VER DEPARTAMENTOS");
        btnDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentsActionPerformed(evt);
            }
        });

        btnCourseStudent.setBackground(new java.awt.Color(132, 244, 217));
        btnCourseStudent.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnCourseStudent.setText("MATRICULAR ASIGNATURA");
        btnCourseStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseStudentActionPerformed(evt);
            }
        });

        btnAddStudent.setBackground(new java.awt.Color(132, 244, 217));
        btnAddStudent.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAddStudent.setText("AGREGAR ESTUDIANTE");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnAddTeacher.setBackground(new java.awt.Color(132, 244, 217));
        btnAddTeacher.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAddTeacher.setText("AGREGAR DOCENTE");
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewDictate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAvailabity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDltStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDepartments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCourseStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddStudent)
                .addGap(5, 5, 5)
                .addComponent(btnAddTeacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateTeacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewDictate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewAvailabity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCourseStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAttendance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDltStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepartments)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStudentActionPerformed
        fMain.updateStudent();
    }//GEN-LAST:event_btnUpdateStudentActionPerformed

    private void btnUpdateTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTeacherActionPerformed
        fMain.updateTeacher();
    }//GEN-LAST:event_btnUpdateTeacherActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        fMain.addInfoCourse();
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnViewDictateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDictateActionPerformed
        fMain.viewDictate();
    }//GEN-LAST:event_btnViewDictateActionPerformed

    private void btnViewAvailabityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAvailabityActionPerformed
        fMain.viewAvailabity();
    }//GEN-LAST:event_btnViewAvailabityActionPerformed

    private void btnScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoreActionPerformed
        fMain.score();
    }//GEN-LAST:event_btnScoreActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        fMain.attendance();
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnDltStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDltStudentActionPerformed
        fMain.dltStudent();
    }//GEN-LAST:event_btnDltStudentActionPerformed

    private void btnDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentsActionPerformed
        fMain.viewDepartments();
    }//GEN-LAST:event_btnDepartmentsActionPerformed

    private void btnCourseStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseStudentActionPerformed
        fMain.addCourseStudent();
    }//GEN-LAST:event_btnCourseStudentActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        fMain.addStudent();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed
        fMain.addTeacher();
    }//GEN-LAST:event_btnAddTeacherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAddCourse;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JToggleButton btnAttendance;
    private javax.swing.JToggleButton btnCourseStudent;
    private javax.swing.JToggleButton btnDepartments;
    private javax.swing.JToggleButton btnDltStudent;
    private javax.swing.JToggleButton btnScore;
    private javax.swing.JToggleButton btnUpdateStudent;
    private javax.swing.JToggleButton btnUpdateTeacher;
    private javax.swing.JToggleButton btnViewAvailabity;
    private javax.swing.JToggleButton btnViewDictate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
