/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import access.clsCourseAccess;
import access.clsTeacherAccess;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.clsDocente;
import model.clsInfoCourse;

/**
 *
 * @author Miguel A. Quevedo P.
 * @correo mquevedo@unicauca.edu.co
 * 
 */

public class JPanelAddInfoCourse extends javax.swing.JPanel {

    private clsTeacherAccess auxTeacherAccess;
    private clsDocente auxTeacher;
    
    private clsCourseAccess auxInfoCourse;
    public JPanelAddInfoCourse() {
        this.auxTeacher = new clsDocente();
        this.auxTeacherAccess = new clsTeacherAccess();
        this.auxInfoCourse = new clsCourseAccess();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblCodeTeacher = new javax.swing.JLabel();
        lblAvailabity = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCodeTeacher = new javax.swing.JTextField();
        txtAvailabity = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JToggleButton();
        lblName1 = new javax.swing.JLabel();
        lblCodeCourse = new javax.swing.JLabel();
        txtCodeCourse = new javax.swing.JTextField();

        lblName.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblName.setText("NOMBRE");

        lblCodeTeacher.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCodeTeacher.setText("CODIGO DOCENTE A CARGO");

        lblAvailabity.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblAvailabity.setText("CUPOS");

        btnAgregar.setBackground(new java.awt.Color(132, 244, 217));
        btnAgregar.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblName1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName1.setText("AGREGAR ASIGNATURA");

        lblCodeCourse.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCodeCourse.setText("CODIGO MATERIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                        .addGap(594, 594, 594))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodeCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodeTeacher)
                            .addComponent(lblAvailabity))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                            .addComponent(txtAvailabity)
                            .addComponent(txtCodeTeacher))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblName1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodeCourse)
                    .addComponent(txtCodeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodeTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodeTeacher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvailabity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvailabity))
                .addGap(35, 35, 35)
                .addComponent(btnAgregar)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Long codTeacher = Long.parseLong(txtCodeTeacher.getText());
        auxTeacher = auxTeacherAccess.SearchTeacher(codTeacher);
        if (!codTeacher.equals("")) {
            if (auxTeacher != null && auxTeacher instanceof clsDocente) {
                addStudent();
            } else {
                JOptionPane.showMessageDialog(this, 
                "No se encontro ningun docente con el codigo:"+ codTeacher,
                "Información",
                JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Hay campos vacios, por favor rellenelos",
                    "informacion",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregar;
    private javax.swing.JLabel lblAvailabity;
    private javax.swing.JLabel lblCodeCourse;
    private javax.swing.JLabel lblCodeTeacher;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JTextField txtAvailabity;
    private javax.swing.JTextField txtCodeCourse;
    private javax.swing.JTextField txtCodeTeacher;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    public void addStudent(){
        try{
		clsInfoCourse objInfoCourse = new clsInfoCourse();
            
		objInfoCourse.setName(this.txtName.getText());
            objInfoCourse.setCode(this.txtCodeCourse.getText());
            objInfoCourse.setCodeTeacher(Long.parseLong(this.txtCodeTeacher.getText()));
            objInfoCourse.setAvailabity(Integer.parseInt(this.txtAvailabity.getText()));
            
		this.auxInfoCourse.AddInfoCourse(objInfoCourse);
            
		JOptionPane.showMessageDialog(this, 
				"Asignatura agregada con exito con Exito",
				"Informacion",
				JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
		}
		catch(NullPointerException e){
			JOptionPane.showMessageDialog(this,
					"Error, No hay espacio",
					"Validar datos",
					JOptionPane.ERROR_MESSAGE);
		}
		catch(NumberFormatException e){
			JOptionPane.showMessageDialog(this,
					"Error, dato mal digitado",
					"Validar datos",
					JOptionPane.ERROR_MESSAGE);
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(this,
					"Error",
					"",
					JOptionPane.ERROR_MESSAGE);
		}
    }
    
    public void limpiarCampos() {
        this.txtName.setText("");
        this.txtAvailabity.setText("");
        this.txtCodeTeacher.setText("");
        this.txtCodeCourse.setText("");
    }
}
