/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import access.clsTeacherAccess;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.clsDocente;

/**
 *
 * @author migue
 */
public class JPanelAddTeacher extends javax.swing.JPanel {

    private clsTeacherAccess auxTeacher;
    public JPanelAddTeacher() {
        this.auxTeacher = new clsTeacherAccess();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblDateBirth = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jDatebirth = new com.toedter.calendar.JDateChooser();
        btnAdd = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 320));

        lblName.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblName.setText("NOMBRE");

        lblDateBirth.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblDateBirth.setText("FECHA DE NACIMIENTO");

        lblId.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblId.setText("NUMERO DE IDENTIFICACION");

        lblCode.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCode.setText("CODIGO");

        lblEmail.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblEmail.setText("EMAIL");

        lblPassword.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblPassword.setText("CONTRASEÑA");

        txtName.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        txtId.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        txtCode.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        txtEmail.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        txtPassword.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(132, 244, 217));
        btnAdd.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAdd.setText("AGREGAR");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateBirth)
                    .addComponent(lblName)
                    .addComponent(lblId)
                    .addComponent(lblCode)
                    .addComponent(lblEmail)
                    .addComponent(lblPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(txtCode)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPassword)
                    .addComponent(jDatebirth, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(txtId))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateBirth)
                    .addComponent(jDatebirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addStudent();
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private com.toedter.calendar.JDateChooser jDatebirth;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDateBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

     public void addStudent(){
        try{
		clsDocente objTeacher = new clsDocente();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            
		objTeacher.setName(this.txtName.getText());
            objTeacher.setDateBirth(formato.format(this.jDatebirth.getCalendar().getTime()));
            objTeacher.setId(Long.parseLong(this.txtId.getText()));
            objTeacher.setCode(Long.parseLong(this.txtCode.getText()));
            objTeacher.setEmail(this.txtEmail.getText());
            objTeacher.setPassword(this.txtPassword.getText());
            
		this.auxTeacher.AddTeacher(objTeacher);
            
		JOptionPane.showMessageDialog(this, 
				"Docente registrado con Exito",
				"Informacion",
				JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
		}
		catch(NullPointerException e){
			JOptionPane.showMessageDialog(this,
					"Error, No hay espacio",
					"Validar datos",
					JOptionPane.ERROR_MESSAGE);
		}
		catch(NumberFormatException e){
			JOptionPane.showMessageDialog(this,
					"Error, dato mal digitado",
					"Validar datos",
					JOptionPane.ERROR_MESSAGE);
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(this,
					"Error",
					"",
					JOptionPane.ERROR_MESSAGE);
		}
    }
    
    public void limpiarCampos() {
        this.txtName.setText("");
        this.jDatebirth.setCalendar(null);
        this.txtCode.setText("");
        this.txtId.setText("");
        this.txtEmail.setText("");
        this.txtPassword.setText("");
    }
}
