/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import access.clsStudentAccess;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.clsStudent;

/**
 *
 * @author Miguel A Quevedo P
 * @email mquevedo@unicauca.edu.co
 */

public class JPanelUpdateStudent extends javax.swing.JPanel {

    private clsStudentAccess auxStudentAccess;
    private clsStudent auxStudent;
    
    public JPanelUpdateStudent() {
        this.auxStudent = new clsStudent();
        this.auxStudentAccess = new clsStudentAccess();
        initComponents();
        jPanel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblTypeDocument = new javax.swing.JLabel();
        lblCareer = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNumDocument = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        cmbTypeDocument = new javax.swing.JComboBox<>();
        lblNumDocument = new javax.swing.JLabel();
        cmbCareer = new javax.swing.JComboBox<>();
        lblDateBirth = new javax.swing.JLabel();
        dateBirth = new com.toedter.calendar.JDateChooser();
        lblCodeStudent = new javax.swing.JLabel();
        txtCodeStudent = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 300));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACTUALIZAR INFORMACION ESTUDIANTE");

        lblName.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblName.setText("NOMBRE");

        lblTypeDocument.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblTypeDocument.setText("TIPO DOCUMENTO");

        lblCareer.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCareer.setText("CARRERA");

        txtName.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        txtNumDocument.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        btnUpdate.setBackground(new java.awt.Color(132, 244, 217));
        btnUpdate.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnUpdate.setText("MODIFICAR");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        cmbTypeDocument.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        cmbTypeDocument.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta de identidad", "Cedula de ciudadania", "Cedula de extranjeria", "Pasaporte" }));

        lblNumDocument.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblNumDocument.setText("NUM DOCUMENTO");

        cmbCareer.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        cmbCareer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artes Plásticas", "Diseño Gráfico", "Dirección de Banda", "Licenciatura en Música", "Música Instrumental", "Ingeniería Agroindustrial", "Ingeniería Agropecuaria", "Ingeniería Forestal", "Tecnología Agroindustrial", "Enfermería", "Fisioterapia", "Fonoaudiología", "Medicina", "Administración de Empresas", "Contaduría Pública", "Economía", "Turismo", "Antropología", "Filosofía", "Geografía del Desarrollo Regional y Ambiental", "Historia", "Licenciatura en Lenguas Modernas con Énfasis en Inglés y Francés", "Licenciatura en Etnoeducación", "Licenciatura en Lingüística y Semiótica", "Licenciatura en Literatura y Lengua Castellana", "Biología", "Ingeniería Física", "Licenciatura en Ciencias Naturales y Educación Ambiental", "Licenciatura en Educación Artística", "Licenciatura en Educación Básica Primaria", "Licenciatura en Educación Física, Recreación y Deportes", "Licenciatura en Matemáticas", "Matemáticas", "Química", "Tecnología en Gestión Ambiental", "Ciencia Política", "Comunicación Social", "Derecho", "Arquitectura", "Ingeniería Civil", "Ingeniería Ambiental", "Geotecnología", "Ingeniería Electrónica y Telecomunicaciones", "Ingeniería de Sistemas", "Ingeniería en Automática Industrial", "Tecnología en Telemática" }));

        lblDateBirth.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblDateBirth.setText("FECHA NACIMIENTO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblName)
                                .addComponent(lblTypeDocument))
                            .addGap(56, 56, 56)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbTypeDocument, 0, 357, Short.MAX_VALUE)
                                .addComponent(txtName)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCareer)
                                .addComponent(lblNumDocument)
                                .addComponent(lblDateBirth))
                            .addGap(45, 45, 45)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNumDocument)
                                .addComponent(cmbCareer, 0, 1, Short.MAX_VALUE)
                                .addComponent(dateBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeDocument)
                    .addComponent(cmbTypeDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCareer)
                    .addComponent(cmbCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnUpdate)
                .addContainerGap())
        );

        lblCodeStudent.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCodeStudent.setForeground(new java.awt.Color(255, 51, 51));
        lblCodeStudent.setText("CODIGO*");

        txtCodeStudent.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        btnSearch.setBackground(new java.awt.Color(132, 244, 217));
        btnSearch.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnSearch.setText("BUSCAR");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblCodeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtCodeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodeStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        try {
            
            Long codEstudiante = Long.parseLong(txtCodeStudent.getText());
            auxStudent = auxStudentAccess.BuscarEstudiante(codEstudiante);
            
            String nombre = txtName.getText();
            String fecha = formato.format(dateBirth.getCalendar().getTime());
            String toDocumento = cmbTypeDocument.getSelectedItem().toString();
            Long numDocumento = Long.parseLong(txtNumDocument.getText());
            String Carrera = cmbCareer.getSelectedItem().toString();
            
            auxStudent.setName(nombre);
            auxStudent.setTypeDocument(toDocumento);
            auxStudent.setCareer(Carrera);
            auxStudent.setEmail(auxStudent.getEmail());
            auxStudent.setPassword(auxStudent.getPassword());
            auxStudent.setDateBirth(fecha);
            auxStudent.setNumDocument(numDocumento);
            auxStudent.setCodeStudent(auxStudent.getCodeStudent());
            this.auxStudentAccess.EditarEstudiante(auxStudent, codEstudiante);
            
            JOptionPane.showMessageDialog(this, 
                "¡ACTUALIZADO CON EXITO!",
                "Información",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "ERROR, por favor contacte al soporte",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Long codEstudiante = Long.parseLong(txtCodeStudent.getText());
        auxStudent = auxStudentAccess.BuscarEstudiante(codEstudiante);
        if (!codEstudiante.equals("")) {
            if (auxStudent != null && auxStudent instanceof clsStudent) {
                clsStudent st = (clsStudent)auxStudent;
                txtName.setText(st.getName());
                cmbTypeDocument.setSelectedItem(st.getTypeDocument());
                txtNumDocument.setText(String.valueOf(st.getNumDocument()));
                cmbCareer.setSelectedItem(st.getCareer());
                jPanel4.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, 
                "No se encontro ningun Estudiante con el codigo:"+ codEstudiante,
                "Información",
                JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Hay campos vacios, porfavor rellenelos",
                    "informacion",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCareer;
    private javax.swing.JComboBox<String> cmbTypeDocument;
    private com.toedter.calendar.JDateChooser dateBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCareer;
    private javax.swing.JLabel lblCodeStudent;
    private javax.swing.JLabel lblDateBirth;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumDocument;
    private javax.swing.JLabel lblTypeDocument;
    private javax.swing.JTextField txtCodeStudent;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumDocument;
    // End of variables declaration//GEN-END:variables
}
