/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import access.clsCourseAccess;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import model.clsCourseStudent;
import model.clsStudent;

/**
 *
 * @author migue
 */
public class JPanelScore extends javax.swing.JPanel {

    private clsCourseStudent auxCourseSt;
    private clsCourseAccess auxCourseAccess;
    private List<clsCourseStudent> lstCourseSt;
    public double limitScore = 3.0;
    public JPanelScore() {
        this.auxCourseSt = new clsCourseStudent();
        this.auxCourseAccess = new clsCourseAccess();
        this.lstCourseSt = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCodeCourse = new javax.swing.JLabel();
        txtCodeCourse = new javax.swing.JTextField();
        btnSearchCourse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCourseSt = new javax.swing.JTable();
        lblCodeSt = new javax.swing.JLabel();
        txtCodeSt = new javax.swing.JTextField();
        lblScore = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        btnScore = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CALIFICACION");

        lblCodeCourse.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCodeCourse.setText("CODIGO MATERIA");

        txtCodeCourse.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        btnSearchCourse.setBackground(new java.awt.Color(132, 244, 217));
        btnSearchCourse.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnSearchCourse.setText("BUSCAR");
        btnSearchCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCourseActionPerformed(evt);
            }
        });

        tCourseSt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO ESTUDIANTE", "NOMBRE ESTUDIANTE", "NOTAS", "ESTADO MATERIA"
            }
        ));
        jScrollPane1.setViewportView(tCourseSt);

        lblCodeSt.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCodeSt.setText("CODIGO ESTUDIANTE");

        txtCodeSt.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        lblScore.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblScore.setText("CALIFICACION");

        txtScore.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        btnScore.setBackground(new java.awt.Color(244, 132, 132));
        btnScore.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnScore.setForeground(new java.awt.Color(0, 0, 0));
        btnScore.setText("INGRESAR NOTA");
        btnScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodeCourse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnSearchCourse))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblScore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodeSt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodeSt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnScore)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodeCourse)
                    .addComponent(txtCodeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodeSt)
                            .addComponent(txtCodeSt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblScore)
                            .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnScore)))
                .addGap(0, 87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCourseActionPerformed
        tableCourse();
    }//GEN-LAST:event_btnSearchCourseActionPerformed

    private void btnScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoreActionPerformed
        addScore();
        tableCourse();
    }//GEN-LAST:event_btnScoreActionPerformed

    public void tableCourse(){
        this.lstCourseSt = this.auxCourseAccess.watchCourseSt();
        String codeCourse = this.txtCodeCourse.getText();
        int counter =0;
        Object matriz[][] = new Object[lstCourseSt.size()][4];
        
        for(int i=0;i<this.lstCourseSt.size();i++){
            if(Objects.equals(codeCourse, this.lstCourseSt.get(i).getCodeCourse())){
                matriz[counter][0] = this.lstCourseSt.get(i).getCodeSt();
                matriz[counter][1] = this.lstCourseSt.get(i).getNameSt();
                matriz[counter][2] = this.lstCourseSt.get(i).getScore();
                matriz[counter][3] = this.lstCourseSt.get(i).getStatus();
                tCourseSt.setModel(new javax.swing.table.DefaultTableModel(matriz,
                        new String[]{"CODIGO ESTUDIANTE",
                            "NOMBRE ESTUDIANTE",
                            "NOTAS",
                            "ESTADO MATERIA"}));
                counter++;
            }
        }
        
    }

    public void addScore(){
        String codeCourse = this.txtCodeCourse.getText();
        double score = Double.parseDouble(this.txtScore.getText());
        Long codeSt = Long.parseLong(this.txtCodeSt.getText());
        
        auxCourseSt = auxCourseAccess.searchCourseSt(codeCourse);
        if (!codeCourse.equals("")) {
            if (auxCourseSt != null && auxCourseSt instanceof clsCourseStudent) {
                clsCourseStudent st = (clsCourseStudent) auxCourseSt;
                st.getCodeSt();
                st.getNameSt();
                st.getEmailSt();
                st.getCodeCourse();
                st.setScore(score);
                st.getAtteandace();
                st.getStatus();
                
                if(st.getScore()<3.0){
                    st.setStatus("PERDIDA");
                }else{
                    st.setStatus("NO PERDIDA");
                }
                auxCourseAccess.upScore(st, codeSt, codeCourse);
                JOptionPane.showMessageDialog(this,
                        "SE REGISTRO "+score+" AL ESTUDIANTE CON EL CODIGO: " + codeCourse,
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE);
                cleanSpace();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se encontro ningun Estudiante con el codigo:" + codeCourse,
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Hay campos vacios, porfavor rellenelos",
                    "informacion",
                    JOptionPane.INFORMATION_MESSAGE);
        }
      
    }
    public void cleanSpace(){
        this.txtCodeSt.setText("");
        this.txtScore.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnScore;
    private javax.swing.JButton btnSearchCourse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodeCourse;
    private javax.swing.JLabel lblCodeSt;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tCourseSt;
    private javax.swing.JTextField txtCodeCourse;
    private javax.swing.JTextField txtCodeSt;
    private javax.swing.JTextField txtScore;
    // End of variables declaration//GEN-END:variables
}
