/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import access.clsStudentAccess;
import javax.swing.JOptionPane;
import model.clsStudent;

/**
 *
 * @author migue
 */
public class JPanelAddStudent extends javax.swing.JPanel {

    /**
     * Creates new form JPanelAddStudent
     */
    private clsStudentAccess auxStudent;
    public JPanelAddStudent() {
        this.auxStudent = new clsStudentAccess();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblTypeDoc = new javax.swing.JLabel();
        lblNumDoc = new javax.swing.JLabel();
        lblCodeStudent = new javax.swing.JLabel();
        lblCareer = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNumDoc = new javax.swing.JTextField();
        txtCodeStudent = new javax.swing.JTextField();
        cmbTypeDoc = new javax.swing.JComboBox<>();
        cmbCareer = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JToggleButton();
        lblName1 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();

        lblName.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblName.setText("NOMBRE:");

        lblTypeDoc.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblTypeDoc.setText("TIPO DE DOCUMENTO:");

        lblNumDoc.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblNumDoc.setText("NUMERO DE DOCUMENTO:");

        lblCodeStudent.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCodeStudent.setText("CODIGO DE ESTUDIANTE:");

        lblCareer.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCareer.setText("CARRERA:");

        txtNumDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDocActionPerformed(evt);
            }
        });

        cmbTypeDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta de identidad", "Cedula de ciudadania", "Cedula de extranjeria", "Pasaporte" }));

        cmbCareer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artes Plásticas", "Diseño Gráfico", "Dirección de Banda", "Licenciatura en Música", "Música Instrumental", "Ingeniería Agroindustrial", "Ingeniería Agropecuaria", "Ingeniería Forestal", "Tecnología Agroindustrial", "Enfermería", "Fisioterapia", "Fonoaudiología", "Medicina", "Administración de Empresas", "Contaduría Pública", "Economía", "Turismo", "Antropología", "Filosofía", "Geografía del Desarrollo Regional y Ambiental", "Historia", "Licenciatura en Lenguas Modernas con Énfasis en Inglés y Francés", "Licenciatura en Etnoeducación", "Licenciatura en Lingüística y Semiótica", "Licenciatura en Literatura y Lengua Castellana", "Biología", "Ingeniería Física", "Licenciatura en Ciencias Naturales y Educación Ambiental", "Licenciatura en Educación Artística", "Licenciatura en Educación Básica Primaria", "Licenciatura en Educación Física, Recreación y Deportes", "Licenciatura en Matemáticas", "Matemáticas", "Química", "Tecnología en Gestión Ambiental", "Ciencia Política", "Comunicación Social", "Derecho", "Arquitectura", "Ingeniería Civil", "Ingeniería Ambiental", "Geotecnología", "Ingeniería Electrónica y Telecomunicaciones", "Ingeniería de Sistemas", "Ingeniería en Automática Industrial", "Tecnología en Telemática" }));
        cmbCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCareerActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(132, 244, 217));
        btnAgregar.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblName1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblName1.setText("Fecha (DD/MM/AA)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(183, 183, 183))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName1)
                        .addGap(73, 73, 73)
                        .addComponent(txtName1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblCareer)
                            .addComponent(lblCodeStudent)
                            .addComponent(lblNumDoc)
                            .addComponent(lblTypeDoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(cmbTypeDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumDoc)
                            .addComponent(txtCodeStudent)
                            .addComponent(cmbCareer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTypeDoc)
                    .addComponent(cmbTypeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumDoc)
                    .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodeStudent)
                    .addComponent(txtCodeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCareer)
                    .addComponent(cmbCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDocActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        addStudent();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCareerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCareerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregar;
    private javax.swing.JComboBox<String> cmbCareer;
    private javax.swing.JComboBox<String> cmbTypeDoc;
    private javax.swing.JLabel lblCareer;
    private javax.swing.JLabel lblCodeStudent;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblNumDoc;
    private javax.swing.JLabel lblTypeDoc;
    private javax.swing.JTextField txtCodeStudent;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtNumDoc;
    // End of variables declaration//GEN-END:variables

    public void addStudent(){
        try{
		clsStudent objStudent = new clsStudent();
            
            objStudent.setName(this.txtName.getText());
            objStudent.setFecha(this.txtName1.getText());
            objStudent.setTypeDocument(this.cmbTypeDoc.getSelectedItem().toString());
            objStudent.setNumDocument(Integer.parseInt(this.txtNumDoc.getText()));
            objStudent.setCodeStudent(this.txtCodeStudent.getText());
            objStudent.setCareer(this.cmbCareer.getSelectedItem().toString());
            
		this.auxStudent.AddStudent(objStudent);
            
		JOptionPane.showMessageDialog(this, 
				"Estudiante registrado con �xito",
				"Informacion",
				JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
		}
		catch(NullPointerException e){
			JOptionPane.showMessageDialog(this,
					"Error, No hay espacio",
					"Validar datos",
					JOptionPane.ERROR_MESSAGE);
		}
		catch(NumberFormatException e){
			JOptionPane.showMessageDialog(this,
					"Error, dato mal digitado",
					"Validar datos",
					JOptionPane.ERROR_MESSAGE);
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(this,
					"Error",
					"",
					JOptionPane.ERROR_MESSAGE);
		}
    }
    
    public void limpiarCampos() {
        this.txtName.setText("");
        this.txtName1.setText("");
        this.txtCodeStudent.setText("");
        this.txtNumDoc.setText("");
        this.cmbCareer.setSelectedIndex(0);
        this.cmbTypeDoc.setSelectedIndex(0);
    }
}
