/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author migue
 */
import acceso.clsVehiculoAccess;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.*;

public class JPanelAddVehiculo extends javax.swing.JPanel {

    private clsParqueadero auxParqueadero;
    private clsVehiculo auxVehiculo;
    private clsVehiculoAccess auxVehiculoAccess;
    public JPanelAddVehiculo(clsParqueadero objParqueadero) {
        this.auxVehiculo = new clsVehiculo();
        this.auxVehiculoAccess = new clsVehiculoAccess();
        this.auxParqueadero = objParqueadero;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitulo = new javax.swing.JLabel();
        jLblPlaca = new javax.swing.JLabel();
        jLblColor = new javax.swing.JLabel();
        jLblCilindraje = new javax.swing.JLabel();
        jLblNumPuertas = new javax.swing.JLabel();
        jLblTipoCaja = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        cmbNumPuertas = new javax.swing.JComboBox<>();
        cmbTipoCaja = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitulo.setText("AGREGAR VEHICULO");

        jLblPlaca.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLblPlaca.setText("PLACA:");

        jLblColor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLblColor.setText("COLOR:");

        jLblCilindraje.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLblCilindraje.setText("CILINDRAJE:");

        jLblNumPuertas.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLblNumPuertas.setText("NUMERO DE PUERTAS:");

        jLblTipoCaja.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLblTipoCaja.setText("TIPO DE CAJA:");

        txtPlaca.setBackground(new java.awt.Color(255, 158, 158));
        txtPlaca.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtColor.setBackground(new java.awt.Color(255, 158, 158));
        txtColor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtCilindraje.setBackground(new java.awt.Color(255, 158, 158));
        txtCilindraje.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        cmbNumPuertas.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmbNumPuertas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No valido", "Dos puertas", "Tres puertas", "Cuatro puertas", "Cinco puertas", " " }));
        cmbNumPuertas.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cmbNumPuertasComponentAdded(evt);
            }
        });
        cmbNumPuertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNumPuertasActionPerformed(evt);
            }
        });

        cmbTipoCaja.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmbTipoCaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No valido", "Dos tiempos", "Cuatro tiempos" }));

        btnRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistrar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("CC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLblNumPuertas)
                            .addComponent(jLblColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblTipoCaja, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCilindraje, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbNumPuertas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipoCaja, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addComponent(txtCilindraje)
                            .addComponent(txtPlaca)
                            .addComponent(txtColor))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCilindraje)
                    .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNumPuertas)
                    .addComponent(cmbNumPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTipoCaja)
                    .addComponent(cmbTipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrarVehiculo();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbNumPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNumPuertasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNumPuertasActionPerformed

    private void cmbNumPuertasComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cmbNumPuertasComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNumPuertasComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbNumPuertas;
    private javax.swing.JComboBox<String> cmbTipoCaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblCilindraje;
    private javax.swing.JLabel jLblColor;
    private javax.swing.JLabel jLblNumPuertas;
    private javax.swing.JLabel jLblPlaca;
    private javax.swing.JLabel jLblTipoCaja;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

    public void registrarVehiculo(){
        try {
            auxVehiculo.setPlaca(this.txtPlaca.getText());
            auxVehiculo.setColor(this.txtColor.getText());
            auxVehiculo.setCilindraje(Integer.parseInt(this.txtCilindraje.getText()));
            auxVehiculo.setCaja(cmbTipoCaja.getSelectedItem().toString());
            auxVehiculo.setPuertas(cmbNumPuertas.getSelectedItem().toString());

            this.auxVehiculoAccess.AddVehiculo(auxVehiculo);
            
            JOptionPane.showMessageDialog(this,
                    "Vehiculo registrado con exito",
                    "Informacion",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this,
                    "Error, No hay espacio",
                    "Validar datos",
                    JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Error, dato mal digitado",
                    "Validar datos",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error",
                    "",
                    JOptionPane.ERROR_MESSAGE);
        }
        limpiarCampos();
    }
    
    public void limpiarCampos() {
        this.txtPlaca.setText("");
        this.txtColor.setText("");
        this.txtCilindraje.setText("");
        this.cmbNumPuertas.setSelectedIndex(0);
        this.cmbTipoCaja.setSelectedIndex(0);
    }
    
}
