/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;
import java.awt.BorderLayout;
import javax.swing.JTextField;

import modelo.*;

import java.awt.Color;
import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JComboBox;

public class JPanelAutomovil extends JPanel implements iGestion {

    private JTextField txtPlacAuto;
    private JTextField txtColorAuto;
    private JTextField txtCilindrajeAuto;
    private JTextField txtNumPuertas;
    private clsParqueadero auxParqueadero;
    private boolean flag = true;

    //CREATE THE PANEL
    public JPanelAutomovil(clsParqueadero objParqueadero) {
        this.auxParqueadero = objParqueadero;

        this.iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void iniciarComponentes() {
        setLayout(null);

        JPanel panel = new JPanel();
        panel.setBounds(0, 0, 696, 24);
        panel.setBackground(new Color(204, 204, 255));
        add(panel);

        JLabel lblAutomovil = new JLabel("AGREGAR AUTOMOVIL");
        panel.add(lblAutomovil);

        JLabel lblPlaca = new JLabel("PLACA:");
        lblPlaca.setBounds(53, 53, 67, 14);
        add(lblPlaca);

        JLabel lblColor = new JLabel("COLOR:");
        lblColor.setBounds(53, 78, 67, 14);
        add(lblColor);

        JLabel lblCilindraje = new JLabel("CILINDRAJE:");
        lblCilindraje.setBounds(53, 103, 100, 14);
        add(lblCilindraje);

        JLabel lblNumPuertas = new JLabel("NUMERO DE PUERTAS:");
        lblNumPuertas.setBounds(53, 128, 139, 14);
        add(lblNumPuertas);

        txtPlacAuto = new JTextField();
        txtPlacAuto.setBounds(202, 50, 138, 20);
        add(txtPlacAuto);
        txtPlacAuto.setColumns(10);

        txtColorAuto = new JTextField();
        txtColorAuto.setBounds(202, 75, 138, 20);
        add(txtColorAuto);
        txtColorAuto.setColumns(10);

        txtCilindrajeAuto = new JTextField();
        txtCilindrajeAuto.setBounds(202, 100, 138, 20);
        add(txtCilindrajeAuto);
        txtCilindrajeAuto.setColumns(10);

        txtNumPuertas = new JTextField();
        txtNumPuertas.setBounds(202, 125, 138, 20);
        add(txtNumPuertas);
        txtNumPuertas.setColumns(10);

        JButton btnRegistrar = new JButton("REGISTRAR");
        btnRegistrar.setBackground(new Color(204, 204, 255));
        btnRegistrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                registrarAuto();
            }
        });
        btnRegistrar.setBounds(214, 175, 112, 23);
        add(btnRegistrar);

    }

    public void registrarAuto() {
        try {
            clsAutomovil objAuto = new clsAutomovil();
            objAuto.setPlaca(this.txtPlacAuto.getText());
            objAuto.setColor(this.txtColorAuto.getText());
            objAuto.setCilindraje(this.txtCilindrajeAuto.getText());
            objAuto.setNumPuertas(Integer.parseInt(this.txtNumPuertas.getText()));

            this.auxParqueadero.agregarAuto(objAuto);
            JOptionPane.showMessageDialog(this,
                    "Auto registrado con exito",
                    "Informacion",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this,
                    "Error, No hay espacio",
                    "Validar datos",
                    JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Error, dato mal digitado",
                    "Validar datos",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error",
                    "",
                    JOptionPane.ERROR_MESSAGE);
        }
        limpiarCampos();
    }

    public void limpiarCampos() {
        this.txtPlacAuto.setText("");
        this.txtColorAuto.setText("");
        this.txtCilindrajeAuto.setText("");
        this.txtNumPuertas.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
